name: Update gist
on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{  }}
          GIST_ID: ${{ https://gist.github.com/gmlwlsdl/e269f4452b75db230c2033f62b5bc104 }}
          TIMEZONE: ${{ Aisa/Seoul }}
